### ISSUE TITLE
Linux compatibility 

### ISSUE THREAD

**Issue by mohsenShakiba** [lisa3907/DotnetPush#1]
Hi,

I was going through your code and realized that it would only work on windows, am I right?

and if so, could you make it linux compatible?

thanks in advance

**Comment by lisa3907** [comment]
Currently running on Ubuntu 16.04.

**Comment by mohsenShakiba** [comment]
well sorry to bother, i shall further investigate the source code.

but just to be clear isn't WinHttpHandler only available on Windows server?

**Comment by lisa3907** [comment]
Use nuget System.Net.Http.WinHttpHandler.dll for .netstandard2.0.

**Comment by mohsenShakiba** [comment]
I keep getting this error:

Unhandled Exception: System.PlatformNotSupportedException: Windows Cryptography Next Generation (CNG) is not supported on this platform.

I'm using Mac should i switch to Ubuntu?

**Comment by lisa3907** [comment]
I recommend Ubuntu 16.04 with dotnet --version 2.1.402.
