### ISSUE TITLE
Error in encoding or decodin

### ISSUE THREAD

**Issue by amwitx** [lisa3907/DotnetPush#2]
code:
var _secret_key_blob = Convert.FromBase64String("MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnrdP+CjGzu7/o1Qs");
PrivateKey = CngKey.Import(_secret_key_blob, CngKeyBlobFormat.Pkcs8PrivateBlob);

error:
System.Security.Cryptography.CryptographicException:“Error in encoding or decoding.”

Is it related to "Pkcs8PrivateBlob"？
Please take a look at it. Thank you.

**Comment by lisa3907** [comment]
> code:
> var _secret_key_blob = Convert.FromBase64String("MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgnrdP+CjGzu7/o1Qs");
> PrivateKey = CngKey.Import(_secret_key_blob, CngKeyBlobFormat.Pkcs8PrivateBlob);
> 
> error:
> System.Security.Cryptography.CryptographicException:“Error in encoding or decoding.”
> 
> Is it related to "Pkcs8PrivateBlob"？
> Please take a look at it. Thank you.

Please upload the entire program source and I'll review it.

**Comment by amwitx** [comment]
I have solved this problem.
Because there is a Bug that reads the P8 file
Split ('\n') [1] is incorrect because you want to read the entire file content
When I change this, I can import the private key.
**code:**
var _private_key_content = System.IO.File.ReadAllText(auth_key_path);//not changed
//////////////////
**string[] list = _private_key_content.TrimEnd('\r', '\n').Split('\n');//add
var _private_key = string.Join("", list.Skip(1).Take(list.Length - 2));//changed**
//////////////////
var _secret_key_blob = Convert.FromBase64String(_private_key);//not changed

Thank you for your reply！
