### ISSUE TITLE
A small suggestion

### ISSUE THREAD

**Issue by amwitx** [lisa3907/DotnetPush#3]
A small suggestion
**New APS Rules**

//iOS 10 and beyond (iOS 7, iOS 8, iOS 9 can use this template)
{
	"Aps": {
		"Alert": {
			"Title": "title".
			"Subtitle": "subtitle".
			"Body": "content"
		}
		"Badge":1,
		"Sound": "default"
	}
}
//iOS before 10
{
	"Aps": {
		"Alert", "content".
		"Badge":1,
		"Sound": "default"
	}
}

**Even support extended generic objects as additional data,** 
such as

"Userinfo": {
	"Playid": "123".
	"Username": "tom"
	"Sex": 1
}

**Or, alternatively, APS packets are generated from the outside, and this project is only transmitted as a channel**

Now, I follow this line of thought to modify it to better support my system.

**Comment by amwitx** [comment]
Sorry, my English is not very good, because I am Chinese.

**Comment by lisa3907** [comment]
JwtAPNsPushExtend function added.

usage

```
var _alert = new {
Title: "title",
Subtitle: "subtitle",
Body: "content"
};

var _apns = new IosPushNotifyAPNs("<key-id>", "<team-id>", "<app-id>", "<key-file-path>");
var _result = await _apns.JwtAPNsPushExtend("<device-token>", _alert, 1, "<sound>")
```
